name: Linux Build

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake libgrpc-dev libssl-dev libboost-program-options-dev

    - name: Configure
      run: cmake -B build -S .

    - name: Build
      run: cmake --build build -j 2

    - name: Install (optional)
      run: cmake --install build --prefix install
